dataSources:
  vmId:
    type: "gce-metadata"
    value: "instance/id"
  vmZone:
    type: "gce-metadata"
    value: "instance/zone"
  vmProjectNumber:
    type: "gce-metadata"
    value: "project/numeric-project-id"
  vmProjectId:
    type: "gce-metadata"
    value: "project/project-id"
  someIpAddresses:
    type: "list"
    value:
      - 192.168.0.1
      - 192.168.0.12
      - 192.168.0.13
      - 192.168.0.14
      - 192.168.0.15
      - 192.168.0.17
      - 192.168.0.19
      - 192.168.0.3
      - 192.168.0.31
      - 192.168.0.33
      - 192.168.0.35
      - 192.168.0.39
  cpuUsageValue:
    type: "random"
    value: "float"
    range: "10.0~99.0"

loggingJobs:
  - startOffset: "-5h"
    frequency: "45s~1m30s"
    textPayload: "Invalid connection request from {ip}"
    level: WARNING
    resourceType: "gce_instance"
    resourceLabels:
      instance_id: "{vmId}"
      zone: "{vmZone}"
    labels:
      activity: "{activity}"
    other:
      trace: "T01234-YXZ"
      http_request:
        requestUrl: "localhost"
    variables:
      - "vmId"
      - "vmZone"
      - name: "activity"
        dataSource: "cpuUsageValue"
      - name: "ip"
        dataSource: "someIpAddresses"
        selector: "any"

metricDescriptors:
  - name: "python_app_count"
    projectId: "{vmProjectId}"
    type: "advobv/queries/python_app_count"
    metricKind: "GAUGE"
    valueType: "DOUBLE"
    unit: "ms"
    description: "This is the Pyhton App metric for the Advanced Observability Querying course."
    displayName: "Python App Count Metric"
    launchStage: "GA"
    labels:
      - key: "python_app_ip"
        valueType: "STRING"
        description: "This is the Pyhton App IP address for the Advanced Observability Querying course."
    monitoredResourceTypes:
      - "gce_instance"
    variables:
      - "vmProjectId"

monitoringJobs:
  - live: false
    startOffset: "-5h"
    frequency: "15s"
    metricType: "advobv/queries/python_app_count"
    metricLabels:
      python_app_ip: "{ip}"
    resourceType: "gce_instance"
    resourceLabels:
      instance_id: "{vmId}"
      zone: "{vmZone}"
    metricValue: "{cpuUsageValue}"
    projectId: "{vmProjectId}"
    variables:
      - "cpuUsageValue"
      - name: "ip"
        dataSource: "someIpAddresses"
        selector: "any"
      - "vmProjectId"
      - "vmId"
      - name: "vmZone"
        extractor: "/zones/([a-z0-9\\-]+)$"
